### ISSUE TITLE
Inconsistent usage of threshold and ratio

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#136]
In order to configure successes, you use a `successThreshold()` and `requestVolumeThreshold()` to specify how many requests need to be successful.

In order to configure failures, you use `failureRatio()` and `requestVolumeThreshold()`

Its assumed that the `successThreshold` is a count of successes, where as for failures you need to calculate this number.  As a user, this is confusing as in one case I need to calculate a threshold where as in the other I need to just list out counts.  It would be better to only use one or the other.

**Comment by Emily-Jiang** [comment]
In the next release, we can make them symmetric. I don't plan for any API changes at this stage.

**Comment by McFoggy** [comment]
as expressed in #188 for me it is the expectations of the TCK tests that are wrong.

Currently I interpret `1.0` as:
- the change from `SEMI_OPEN` to `CLOSE` depends on `successThreshold()` consecutive success calls
- a change to `OPEN` depends on a `failureRatio()` failures over a window call of `requestVolumeThreshold()`

but I might be wrong in my reading of the API/specs.

Nevertheless, it can valuable to adapt the `SEMI-OPEN` to `CLOSE` step to use a ratio instead of a consecutive number of successful calls.

**Comment by Emily-Jiang** [comment]
@McFoggy your interpretation was correct. will work on this issue shortly.

**Comment by Emily-Jiang** [comment]
maybe we can introduce successRatio to specify the success ratio.

**Comment by Emily-Jiang** [comment]
We discussed this issue in today's hangout. If we introduce the symmetric methods, it will create confusion and conflict if a developer specify both successratio and successThreshold. Which one to win? Besides, these parameters are configurable, it is unclear which value will have the final say. The current methods are sufficient to make the circuit breaker configurable and usable. It could be nice to have the symmetric behaviour but the disadvantage overweights the benefit.
