### ISSUE TITLE
tck on a jee container fail with NPE

### ISSUE THREAD

**Issue by McFoggy** [eclipse/microprofile-fault-tolerance#165]
While implementing FT as a standard JEE CDI extension, I am facing issues running the TCK.  
Given the attached simple demo project (tck+arquillian+wildfly), running `mvn test` ends with:

```
Results :

Failed tests:
  RetryTest>Arquillian.run:164->testClassLevelRetryMaxDuration:159 NullPointer
  RetryTest>Arquillian.run:164->testClassLevelRetryMaxDurationSeconds:184 NullPointer
  RetryTest>Arquillian.run:164->testClassLevelRetryMaxRetries:138 NullPointer
  RetryTest>Arquillian.run:164->testRetryMaxDuration:91 NullPointer
  RetryTest>Arquillian.run:164->testRetryMaxDurationSeconds:106 NullPointer
  RetryTest>Arquillian.run:164->testRetryMaxRetries:76 NullPointer
  RetryTest>Arquillian.run:164->testRetryWithDelay:119 NullPointer

Tests run: 7, Failures: 7, Errors: 0, Skipped: 0
```

Not being an expert of [testng](http://testng.org), I have read on [SO](https://stackoverflow.com/questions/10230710/beforeclass-annotations-invoking-methods-twice-when-using-arquillian-on-remote#answer-17036231) that injection occured both client and server side for deployed tests. Also [testng](http://testng.org) documentation states that injection is handled directly by testng or guice, which might collide with CDI+Arquillian.

How can the tck be run using a jee container?

**Example maven project:** [jee-mpft.zip](https://github.com/eclipse/microprofile-fault-tolerance/files/1340135/jee-mpft.zip)

**Comment by hutchig** [comment]
All the @Inject variables in the test are null so it is injection that is not working (as you allude to) from looking at https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java  at the line numbers above. We run this test (without edits) in Liberty. There is a ' .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml")' in the test - is there something else in wildfly that needs to be done to get it to see the beans and recognise the 'business methods'.  Another factor is your equivalent of https://github.com/arquillian/arquillian-container-was/blob/master/wlp-managed-8.5/src/main/java/org/jboss/arquillian/container/was/wlp_managed_8_5/WLPManagedContainer.java which actually does the deploy?    You can mess with the war via something like a https://github.com/struberg/javaConfig/blob/master/impl/src/test/java/org/apache/geronimo/config/test/GeronimoConfigArchiveProcessor.java (for example I have had cause to add a hamcrest jar due to  https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

**Comment by hutchig** [comment]
It may be that CDI (Weld) is putting out messages on why it cannot inject an instance of the bean classes used in the test. Without a bean, there is nothing to for the FT interceptors to intercept. The war is built the same for different environments so perhaps it is something to do with the deploy or container - and there might be some messages from Wildfly?

**Comment by McFoggy** [comment]
@hutchig for me this is not a CDI issue. The errors are coming from the client part in which CDI should not be involved.
In arquillian tests, when junit is used and that the arquillian test is not "client side", then the test is fully run "on the container".  
Here the problem is that _testng/arquillian_ is trying to execute "client side" some code that **MUST** run on the container.

**Comment by McFoggy** [comment]
Also notice that using #166, the exact same project can run the tck on wildfly.
So there is really something related to testng/arquillian that goes wrong and that lead to the above failures.

**Comment by McFoggy** [comment]
> using hamcrest it but it not being in Liberty

this is also why I proposed to open a kind of extension point in arquillian tck tests, see #166 beb2cab1a10cca86294d1a8d371a8098d374cd5e

**Comment by Emily-Jiang** [comment]
@McFoggy MicroProfile spec TCKs all use Aquillian framework. I think @starksm64 has got the jwt tck or config tck running successfully against wildfly. Can you get in touch with him and borrow some ideas? I don't think FT should be the odd one out, not following the MP tck framework. Also Weld team has expertise to run Aquillian tcks.

**Comment by McFoggy** [comment]
@Emily-Jiang thanks I'll contact him to understand what is failing with this testng/arquillian/wildfly combo while everything goes well with junit/arquillian/wildfly.

Can you please also give your thoughts on opening the tck for some extension mechanisms allowing to include "implementation/additions" to run the tck (see beb2cab1a10cca86294d1a8d371a8098d374cd5e).
Such an extension mechanism would allow to introduce implementations into the tck tests without having to modify the tck itself or without having to hook into containers internals at a lower level.

**Comment by hutchig** [comment]
I left comments on #166

**Comment by McFoggy** [comment]
@Emily-Jiang still I did not get any answer from @starksm64 until now but I looked at the repos he contributed to and I found [wildfly-extras/wildfly-microprofile-config](https://github.com/wildfly-extras/wildfly-microprofile-config).  
Were you refering to that project for the tck tests run under wildfly? 
If so then it looks like in fact the arquillian tests are run against openwebbeans (see https://github.com/wildfly-extras/wildfly-microprofile-config/blob/master/tck/pom.xml#L99) and not against wildfly.

**Comment by johnament** [comment]
@McFoggy I think your issues are wildfly swarm related only.  We all use archive appenders to manipulate the WAR file.I'm not sure you can do that in Swarm.

**Comment by McFoggy** [comment]
@johnament I do not use swarm., I just tried to run the tck using a wildfly standalone installation via arquillian. 

If I was not clear, it is perfectly running if I use the junit version from #166. But using the standard provided tck with testng it fails.

**Comment by johnament** [comment]
Hmm I suspect we need the Dr's of Arquillian to give some input, your pom configuration looks off (would be better if you could point to a repo for this rather than a download) but I'm not too familiar with universe to really weigh in.

FWIW, I've been able to get Geronimo Config testing against wildfly, and it works with some tweaks.

@bartoszmajsak or @lordofthejars ?

**Comment by Emily-Jiang** [comment]
I talked with @starksm64 at JavaOne and asked him in person to help you out @McFoggy. He will be in touch to help you.

**Comment by McFoggy** [comment]
@johnament @Emily-Jiang @starksm64 I finally got it running by moving to latest version of arquillian universe [McFoggy/mpft-jee-tck#60c4bc33cd2ba584f9db80a0b423fd60c1921f6f](https://github.com/McFoggy/mpft-jee-tck/commit/60c4bc33cd2ba584f9db80a0b423fd60c1921f6f)

Thus by using [McFoggy/mpft-jee-tck](https://github.com/McFoggy/mpft-jee-tck) and running `mvn integration-test -Dit.test=RetryTest`, we see the FT tck Retry related tests executed on wildfly.
The tests this time are failing due to the tck assertions (which is expected) and not because of the weird injection error we could saw before.

**Comment by Emily-Jiang** [comment]
Great news! Thanks for the update @McFoggy !
