### ISSUE TITLE
CircuitBreakerTest tests are not independants

### ISSUE THREAD

**Issue by McFoggy** [eclipse/microprofile-fault-tolerance#210]
#201 introduced new tests reusing injected services.

That means that between 2 tests using the same service (for ex: `testCircuitDefaultSuccessThreshold() & testCircuitInitialSuccessDefaultSuccessThreshold()` use both `clientForCBDefaultSuccess`) the CircuitBreaker implementation retains information from previous test.

This is an issue especially for remote implementations that deploy the test artifact once and play all the tests methods on this single deployment and thus retaining info from one test to the other.

**Comment by johnament** [comment]
@McFoggy is this an implementation bug?  I would expect on redeploy that the data is reset, not persisted.  but perhaps that's my own implementation assumption.

**Comment by McFoggy** [comment]
@johnament for me it is not implementation dependent. It is just that it might appear with only remote implementations.   
Problem is that using arquillian the deployment is done once for all tests in file, and as the tests reuse the same service, for which the impl must keep track of calls, the second test does not start in a clean state.

**Comment by Emily-Jiang** [comment]
@neilgsyoung can you take a look at this?

**Comment by neilgsyoung** [comment]
The reason it worked for me is that the OpenLiberty environment where I test uses a managed Liberty container, so that 2 JVMs are in operation. The first JVM drives the tests against the second JVM where the Liberty server runs. In that environment the tests are independent because the client service's bean is Request Scoped. 

For other environments, one simple way to ensure that we re-initialize at the start of each test is to reset counterForInvokingServiceA to zero. I suggest that's what I do.
