### ISSUE TITLE
Add metrics status automatically for FT

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#234]
Based on the feedback we got from the community, we need to display the metrics for FT actions.

Look at each annotation in turn:
1. Retry - it might be useful to display the time of retries. Maybe @Counter can be automatically added.

2. Timed - ideally it is good to display how long each method takes to run. @Timer can be used.
3. CircuitBreaker - good to list the failure rate, circuit open time, request ranges etc. Histogram can be used?

4. Bulkhead - nice to list the waiting requests, how long it waited etc, @Gauge can be used?

**Comment by Azquelt** [comment]
I've tried to follow prometheus best practices, particularly on [instrumentation][1] and [naming of metrics][2].

To make sense of the metrics I've suggested, it should be noted that prometheus will collect a snapshot of all of the metrics on a regular basis (default every 15 seconds) and provides lots of facilities for comparing and processing collected metric data.

For example, while a counter of the number of calls made to a method isn't useful on its own, it can be used in the following ways:
 - it can be fed into the `rate()` function to produce a graph of the rolling average rate of calls per second over the last minute
 - if you also have a count of the calls which failed, you could also divide the failures per second by the total calls per second to see what proportion of calls to the method are failing over time

# Proposed metrics

For `@Retry`:
 - Counter of calls (`${name}_calls_total`)
 - Counter of retries (`${name}_retries_total`)
 - Counter of calls which failed despite retrying (`${name}_failures_total`)

Rationale: 
 - User knows that they're calling an unreliable API so it may be worthwhile to monitor how unreliable it is so that they can see when it's approaching the point where it may impact the system.

For `@Timeout`:
 - Histogram of execution times (`${name}_duration_seconds`)
 - Counter of calls (`${name}_calls_total`)
 - Counter of timeouts (`${name}_timeouts_total`)

Rationale:
 - User is concerned about how long the method takes to return, so we should monitor this

For `@CircuitBreaker`:
 - Gauge of breaker state (`${name}_breaker_open`)
   - should we include a % time open?
 - counter of calls (`${name}_calls_total`)
 - counter of failures (`${name}_failures_total`)
 - counter of failures caused by the breaker being open (`${name}_breaker_open_failures_total`)

Rationale:
 - User is concerned about API breaking to the point that they'd just rather not use it until it's working again. We should monitor how close we're getting to that threshold and how often we're crossing it.

For `@Bulkhead`:
 - Gauge of number of current executions (`${name}_current_executions`)
 - Counter of calls (`${name}_calls_total`)
 - Counter of rejections (`${name}_rejections_total`)
 - Gauge of queue length (async only) (`${name}_queue_length`)

Rationale:
 - User is worried about contention of a limited resource. They may be interested in: how many calls are currently executing, how many calls are made, how many calls are rejected, how long the queue is (async only)

Note that some of the annotations produce the same metrics (e.g. all of them count the number of calls). If the user applies two annotations to the same method, only one copy of any duplicated metrics would be produced.

# Naming

All FaultTolerance metrics would have some sort of common prefix, as suggested in eclipse/microprofile-metrics#169

The user should be allowed to define a more meaningful name for their metric if desired. I'd suggest following the same pattern that MP Metrics uses to allow users to name metrics added by annotations:
 - The user can manually set the metric name by annotating the method or class. I would suggest a new annotation in the FaultTolerance spec - `@FTMetrics(name="myName", absolute=true)`
 - If no such annotation is present, a name would be automatically generated based on the fully qualified name of the class or method.

# Aggregation

Sometimes it makes sense to aggregate the metrics from several methods (e.g. all the methods for querying a particular remote API). I would suggest mimicing the way MP Metrics does this by allowing the user to annotate two methods with the same name using `@FTMetrics(name="myName", reusable="true")`. The metrics from these two methods would then be combined in the output.

# Configuration

We should allow the user to globally enable or disable FT metrics.

# Open questions
 - labels
   - Currently MP Metrics does not support reporting two metrics with the same name but different labels, see eclipse/microprofile-metrics#59. If this functionality were added, I would suggest combining the counters for total calls and failures into `${name}_calls_total(result="success|failure" failure_reason="exception|timeout|breaker_open|bulkhead_full")`
 - interaction with MP Metrics annotations
   - E.g. if a method is annotated with `@Retry` and `@Counted`, if the method fails, gets retried and then succeeds, should the counter for `@Counted` be incremented once or twice? I'm not sure what happens at the moment.

[1]: https://prometheus.io/docs/practices/instrumentation/
[2]: https://prometheus.io/docs/practices/naming/

**Comment by Azquelt** [comment]
Back from holiday, I've updated the comment above with the changes suggested at the hangout on 2018-03-14

* CircuitBreaker
  * Add accumulated open/closed time
  * Add counter for number of times circuit breaker opens
  * Add gauge for the current fail rate of the circuit breaker window
* Bulkhead
  * Change `current_executions` to `concurrent_executions`
  * Change `queue _size` to `queue_population`
  * Add histogram of execution times
  * Add histogram of time spent waiting in queue

**Comment by Emily-Jiang** [comment]
@pilhuhn @donbourne please read @Azquelt 's suggestion to see whether you have any comments.

**Comment by pilhuhn** [comment]
I think that mostly makes sense. I am a bit worried about the new `@FTMetrics` annotations that duplicate some of what metrics has. Perhaps we can find a better way to use `@Metric` here, as I feel confusion coming up when both exists.

The other thing that we are working on and that we still need to solve is where in the metrics registries those metrics would be registered. Originally in eclipse/microprofile-metrics#169 I thought we would have a new scope next to 'base','vendor' etc, but the current thinking goes more along the way of putting that into the 'application' space -- especially as we consider supporting more than one application per server (which partially violates the µService idea), as it would allow to use MP-Metrics also in more classic scenarios. In this case the FT data would perhaps end in application/<name>/_ft/ (and in respective places depending on the exporter).  I wrote my thoughts down a while ago here: https://gist.github.com/pilhuhn/3fd62a2447edd027bd607503c75b3abe but this needs more work.

**Comment by Azquelt** [comment]
@donbourne sorry for not responding sooner, work has been quite hectic as people are away.

1) Yes, that sounds like a good idea. I'll add that.
2) Yes, that makes sense too, though I'm a little concerned that it would negatively impact the usability. Summing across a bunch of tagged metrics is easy, you just put `sum(` and leave out the tag, but summing when you have to name several long metric names is a pain. You could do a regex match on the `__name__` label but this makes it less intuitive. For this reason I'd be tempted to keep some of the total metrics. I've had a brief read but need to go through your proposal in more depth.
3) I'm not sure about this. My concern was around aggregating metrics gathered from calls to several different methods. I don't really like the data duplication you get when you split out the metrics like that by annotation as several of them add the same data. I'm not sure whether it improves the situation when it comes to aggregating across methods either.
4) I agree that if we go ahead with (3) then this makes sense.

I also realised that I probably need to specify the metrics in terms of the metrics API, not in terms of the prometheus output, since the metrics feature also outputs to a json format which exposes all the metadata and doesn't convert all values to base units. That will change the names slightly (and also makes some of the names impossible as the prometheus output always appends the unit to the name, so you can't have anything following that). **Does that make sense?**

Also, while starting to write the TCK, I couldn't find an API to retrieve the metadata for a metric. **Does one exist?**

**Comment by Azquelt** [comment]
Having re-read your suggesting for renaming the metrics to make it easier to transform them to tagged metrics at a later point, I think the suggestions are great.

We could also possibly make the `${name}` section a tag as well. That would allow you to write queries like "what are the top 10 methods with the worst 99th percentile execution time", and "which methods need to retry more than 2% of the time".

I think on balance I'm ok with putting the annotation name in the metric name. It does create a bit of redundancy, but it also makes it clearer whether we're talking about number of calls from the outside, or number of attempts under a `@Retry` annotation.

**Comment by Azquelt** [comment]
I've taken Don's changes and submitted a PR for these changes to the spec.

I also made the following changes
* Removed the gauge showing the internal state of the circuit breaker, I couldn't find a way to get this out of Failsafe
* Renamed `ft_${name}_circuitbreaker_calls_failure_open_total` to `ft_${name}_circuitbreaker_calls_circuit_open_total`
* Added metrics for the circuit breaker half-open state

Still have the following questions:
* Naming and aggregation - so far my PR doesn't allow for either custom names or aggregating metrics from several methods
  * Also realised that aggregating some of the gauges is impossible, e.g. how do you report that one circuit breaker is open while another one is closed
* What should we do where a bean has two methods which have the same name but different arguments?
  * At the moment, they will generate metric names that clash

**Comment by OndrejM** [comment]
I suggest to resolve the current comments on the #257 PR, merge it in and continue the discussion here.

My opinion:
- **gauge for internal CB state** - any gaps in an existing implementation shouldn't prevent adding features into a spec, therefore I would bring back the metric with the current state of a circuit breaker. Implementations should add support for it to be compatible, not the other way around.
- **naming and aggregation** - this isn't a blocker and we can defer it to a future release if not resolved soon
- **methods with the same name** - we need to resolve this, not sure how
- **registered at application startup** - I would leave this as an implementation detail. The spec can say that eager initialization is recommended but not mandated.

**Comment by donbourne** [comment]
My thoughts...
- **naming and aggregation** - I have opened issue https://github.com/eclipse/microprofile-metrics/issues/237 to address that on the mpMetrics side.  I expect this will require another feature in mpMetrics (which would require another release of mpMetrics to exploit it).  In the meantime, you may need to use an inferred name.  As a suggestion, the inferred name could be the class name plus the method name plus a hashcode generated from the package name, and method signature.
- **methods with the same name** - one solution to this will be to let users specify an absolute metric name and reuse setting (once mpMetrics issue 237 is addressed).  Short term solution could be what I suggested above for the inferred name.
- **registered at application startup** - it is important that implementations be allowed to have lazy initialization for metrics.  I'm not sure I would state a preference for eager initialization in the spec as that would only be practical for more static/monolithic servers/apps.

**Comment by donbourne** [comment]
On second thought, I'm not sure I like the idea of your inferred name differing from mpMetrics inferred name.  I think that changes my thoughts to...

- **naming and aggregation** - wait for eclipse/microprofile-metrics#237
- **methods with the same name** - wait for eclipse/microprofile-metrics#237.  In meantime, use reusable=true and tell people that multiple methods with same name will be tracked by the same metrics.
- **registered at application startup** - it is important that implementations be allowed to have lazy initialization for metrics. I'm not sure I would state a preference for eager initialization in the spec as that would only be practical for more static/monolithic servers/apps.
