### ISSUE TITLE
Asynchronous execution with retry policy - clarify if a Future that completes exceptionally triggers a retry

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#246]
This issue is related to #245. See also the following example. Note that the `Future` might be actually obtained from another part of the app.

````java
@Asynchronous
@Retry(maxRetries = 2)
public Future<String> retry() throws IOException {
   CompletableFuture<String> future = new CompletableFuture<>();
   future.completeExceptionally(new IOException("Simulated error"));
   return future;
}
````

**Comment by Emily-Jiang** [comment]
It should trigger the retry if a Future that completes exceptionally. We should add tests for this.

**Comment by mkouba** [comment]
If so, the spec should clarify that the `Future` returned is an internal construct which delegates to a `Future` returned from the method.

**Comment by OndrejM** [comment]
We should also mandate that if FT annotations are applied on an `@Asynchronous` method, they finish the future exceptionally instead of throwing an exception from the method. As discussed in #250

**Comment by ggam** [comment]
Any chance to get this for the next version? Can I help here?

**Comment by Emily-Jiang** [comment]
Let's try to get this done for FT 2.0.

**Comment by Emily-Jiang** [comment]
@brunobat will take a look to contribute some tcks.

**Comment by Azquelt** [comment]
We discussed this a little on the hangout this week and I don't think this is possible for methods which return a `Future`.

There's no way to trigger something to run when a `Future` completes, you can only probe it to see if it's done yet. If we wanted to apply `Retry` around the completion of a Future, we'd either have to dedicate a thread to waiting for the Future to finish, have a background task which periodically polls Futures to see if they're done yet or only actually do the Retry when someone calls `get()`. None of those options seem like a good idea.

For a `CompletionStage` it's possible because we can add an action to be run after the `CompletionStage` completes.

**Comment by OndrejM** [comment]
Hi, I think that we can easily support Future with the same semantics as for synchronous executions after `Future.get()` is called. I explain it https://github.com/eclipse/microprofile-fault-tolerance/issues/362#issuecomment-448502738.

I wasn't on the hangout on 28 Nov so I may be missing some arguments. But the argument in the meeting minutes isn't really valid: "Future that ends in an exception cannot be retried because the get() can only be called once". This is simply because a failed call can be executed within the Future, within a single `get()` call. However, as I explained in my comment above, this may not be worth to specify and implement and a deprecating `Future` is also a good option.

**Comment by Emily-Jiang** [comment]
Let's clarify that in the spec `Future` is less favored and we should recommend end users to go with CompletionStage instead. For `Future`, we only do FT around method invocation instead of returned future result.
