### ISSUE TITLE
Investigate how Asynchronous works with other annotations

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#291]
We need to spec what is the desired behavior for the following use cases:

- Use Asynchronous with Timeout

```
@Asynchronous 
@Timeout
public CompletionStage callA() {


}
```

- Use Asynchronous with CircuitBreaker
```
@Asynchronous 
@CircuitBreaker
public CompletionStage callA() {


}
```
- Use Asynchronous with Retry
```
@Asynchronous 
@Retry
public CompletionStage callA() {


}

```
-  Use Asynchronous with Bulkhead
```
@Asynchronous 
@Bulkhead
public CompletionStage callA() {


}
```

-  Use Asynchronous with Fallback
```
@Asynchronous 
@Fallback(fallbackMethod="myFallback")
public CompletionStage callA() {


}
```

**Comment by Emily-Jiang** [comment]
```
- Use Asynchronous with Retry
```
@Asynchronous 
@Retry
public CompletionStage callA() {


}

```

If an exception occurs for callA(), the retry will be triggered on a different thread.

- Use Asynchronous with Timeout

```
@Asynchronous 
@Timeout
public CompletionStage callA() {


}
```
If timeout duration reaches, interrupt/cancel the thread. Throw TimeOutException as soon as Timeout reaches its duration. 

-  Use Asynchronous with Bulkhead
```
@Asynchronous 
@Bulkhead
public CompletionStage callA() {


}
```
This means multithreading style of bulkhead.
-  Use Asynchronous with Bulkhead and Timeout
```
@Asynchronous 
@Bulkhead
@Timeout
public CompletionStage callA() {


}
```
The timeout starts from the request is being made. Timeout starts the request is put on the queue. If timeout occurs, if the thread is on the waiting queue, it will be removed from the waiting queue. If the thread is running, the thread will be interrupted/cancelled. TimeoutException will be thrown.

-  Use Asynchronous with Bulkhead, Retry and Timeout
```
@Asynchronous 
@Bulkhead
@Timeout
@Retry
public CompletionStage callA() {


}
```
The timeout starts from the request is being made. Timeout starts the request is put on the queue. If timeout occurs, if the thread is on the waiting queue, it will be removed from the waiting queue. 
If the thread is running, the thread will be interrupted/cancelled. 
The TimeoutException will be thrown, which will trigger Retry. Retry will be on a separate thread.
- Use Asynchronous with CircuitBreaker
```
@Asynchronous 
@CircuitBreaker
public CompletionStage callA() {


}
```
If a configured failure rate occurs, CircuitBreakerOpenException will occur. Any subsequent requests will complete immediately with  CircuitBreakerOpenException.

**Comment by Emily-Jiang** [comment]
We are going to discuss this and make decision on 11th July. Please attend the call then.

**Comment by Emily-Jiang** [comment]
- Use Asynchronous with Retry, CircuitBreaker
```
@Asynchronous 
@Retry
@CircuitBreaker
public CompletionStage callA() {


}

```

1. callA() -> retry 3 times ()
2. callA() -> retry 3 times ()
3. callA() ->retry 3 times ()
4. callA() ->retry 3 times ()
5. callA() ->retry 3 times ()


callA() fails, retry will happen, circuitbreaker

**Comment by Azquelt** [comment]
Can we clarify the following:

`@Retry` + `@Timeout` - does each retry attempt start a new timeout?

`@Timeout` + `@CircuitBreaker` - is the `TimeoutException` counted as a failure by the circuit breaker?

`@Timeout` + `@Bulkhead` + `@Asynchronous` - We said that the `TimeoutException` is thrown immediately and the running method is interrupted. Does the execution still take up a bulkhead running slot until it actually returns?

`@Timeout` + `@Retry` + `@Asynchronous` - We said that the `TimeoutException` is thrown immediately and the running method is interrupted. Does this mean that we can start a retry attempt immediately, even while the original timed-out attempt may still be running? If so, is this behaviour required or optional?

**Comment by Azquelt** [comment]
I found one that I missed:

1. `@Bulkhead` + `@CircuitBreaker` - how do these work together? When do we check whether the circuit breaker allows execution relative to when we attempt to acquire a slot from the bulkhead? Is a `BulkheadException` counted as an execution failure by the circuit breaker?

**Comment by Azquelt** [comment]
Have we now covered this adequately with #314 and #333 ?

**Comment by OndrejM** [comment]
@Azquelt @Emily-Jiang @antoinesd 

I'm still missing description of what happens, if methods complete really asynchronously, with Future/CompletionStage completed (succesfully or exceptionally) after methods return. All interceptors should expect asynchronous results and defer their action until the result/exception is available.

This is also raised in #249 specifically for Circuit Breakers.

All the asynch. tests in #333 return a completed future, which doesn't cover this usecase. The tests don't ensure that interceptors handle the methods asynchronously, an implementation can simply wait for the method to complete and handle it in a synchronous way to pass the tests. 

We need to clarify what happens if methods return a future which isn't completed yet. Interceptors should wait for the result, and handle exceptions from the future, not only from the original method.

Is it better to raise a separate issue for that? Or extend #249 to cover all other interceptors?

**Comment by OndrejM** [comment]
In short, to summarize my comment above, only to clarify that `@asynchronous` works with other annotations and that it is triggered first before all other annotations isn't useful. If the user is expected to return a completed future from the method, then using CompletableFuture isn't transparent.

**Comment by Azquelt** [comment]
Hey @OndrejM, thanks for your analysis.

1. Reading over the spec again, I think you're right that we're not clear enough about whether the fault tolerance actions take effect around the method call itself or around the returned Future/CompletionStage completing. The spec should be clearer on the expected behaviour that and we should have tests for returning an incomplete Future/CompletionStage.

2. I agree that having interceptors wait for the result from a `Future` or `CompletionStage` would be good. We're looking at doing that under #246, but I don't think it's possible to do it in a reasonable way for a `Future`.
