### ISSUE TITLE
Specify that CircuitBreaker should break if threshold is met before requestVolumeThreshold sliding window is full

### ISSUE THREAD

**Issue by derekm** [eclipse/microprofile-fault-tolerance#324]
If the `requestVolumeThreshold` has not yet been met, but the initial observations surpass `requestVolumeThreshold`*`failureRatio` failures, then the CircuitBreaker should open the circuit.

E.g., if `requestVolumeThreshold` is 6, and `failureRatio` is 0.5, then 6*0.5 is 3. If the first 3 observations are failures, the threshold has been met, and the circuit can be opened.

We have unit tests for Geronimo Safeguard showing that it ignores the first 3 failures until the count of observations exactly matches `requestVolumeThreshold`.  For example, we can send in 3 failures and the circuit won't open. We can then send in 3 successes, and the circuit will then open, somewhat ironically.

We should contribute our unit tests to Safeguard so it can consider if a fix is in order, but perhaps there is also something more to add or clarify in the MP FT spec.

Cc: @johnament, @ivangreene

**Comment by Emily-Jiang** [comment]
Yes, this is expected behaviour. The requstVolumeThreshold should be met first and then check the failure ratio. If the failure ratio is met, then circuit will be open. Remember this is rolling window. The first threadshold needs to be met first. After that, it will cut the last consecutive requests. e.g.

if requestVolumeThreshold is 6, and failureRatio is 0.5, if the first 3 executions failed, it does not trick the circuit to open as it needs to check every 6 operations. You might think it does not make sense. However, it does, if you think the requests will be continuous till 40. The system will check the last 6 consecutive executions, it then trick the circuit to open if failure ratio is reached.

**Comment by derekm** [comment]
@Emily-Jiang -- Yes, I think you're right. My tests were putting me on an artificial time horizon. In a continuously running system, I don't really need to worry about short-circuiting thresholds outside of the 1st pass through the sliding window.

Is there absolutely no value to the different dynamics provided by short-circuiting thresholds during the 1st pass through the sliding window? I think maybe not, but I'm unsure.

Thanks for the explanation/reminder!

**Comment by Azquelt** [comment]
Is this resolved? Can the issue be closed?
