### ISSUE TITLE
Don't block current thread on retry with delay

### ISSUE THREAD

**Issue by ggam** [eclipse/microprofile-fault-tolerance#327]
Looking at Payara and SmallRye implementations of the `@Retry` interceptor, I found that both sleep the current thread when `@Retry` is used with a delay. That can be dangerous when the request is not being processed asynchronously, as it will block a request thread from the pool. If the error was caused due to a recurrent problem (e.g. some depended service unavailability), lots of request threads might end up being blocked waiting, saturating the whole server.

My expectation was that the request thread would be freed and reclaimed after the delay has completed.

Now, I think there might be a technical difficulty in doing that. It should be easy to do for methods returning a `CompletableFuture` (related to #246), by registering more stages into the pipeline. This would work everywhere `@Retry` is used, being it JAX-RS resources or plain CDI beans.

For the specific case of JAX-RS, I've made the attempt to wrap the returned object with a `CompletableFuture` to see if the runtime was able to handle it:
```
@Interceptor
@RetryAsync
@Priority(Interceptor.Priority.PLATFORM_AFTER + 5)
public class RetryAsyncInterceptor {

    @AroundInvoke
    public Object aroundInvoke(InvocationContext ic) throws Exception {
        try {
            return ic.proceed();
        } catch(Exception e) {
            if(!ic.getMethod().getReturnType().equals(CompletableFuture.class)) {
                // Return type is not CompletableFuture. Wrap it
                return CompletableFuture.<Object>supplyAsync(() -> {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        return new RuntimeException(ex);
                    }
                }).thenAccept((s) -> {
                    // TODO: make sure it runs again on current thread again
                    try {
                        ic.proceed();
                    } catch (Exception ex) {
                        return new RuntimeException(ex);
                    }
                });
            }
           
            return ic.proceed();
        }
    }
}
```

Obviously, it didn't :)

So my two proposals are:
- Clarify that the delay should not block the calling thread when the intercepted method returns a `CompletableFuture`.
- Look for a way to make it always work when the intercepted method is a JAX-RS resource. If there's no portable way right now, do you think my idea above is worth proposing to JAX-RS, or do you have any better solution?

**Comment by Azquelt** [comment]
With @Retry and @Asynchronous, it's possible to release the thread and schedule a new task for the retry.

It's not possible to do that when not using @Asynchronous because all execution happens on the same thread.

In addition, no call should block the calling thread when using @Asynchronous. I think that's now explicit in the spec.

I'm unsure whether it should be explicitly specified that when using @Retry with a delay and @Asynchronous together, the thread must be released when doing the delay as I think that would be tricky to verify.

Lastly, you talked about changing the behaviour if the return type is a `CompletableFuture`. I'd be against this. The current spec does change the behaviour when @Asynchronous is used (which in turn requires that the method's return type is `Future` or `CompletionStage`).

I think we should only change the behaviour based on the fault tolerance annotations used, and not based solely on the return type of the method.

**Comment by ggam** [comment]
I think I might have failed to explain my point. Let my try again.

I don't need the method call to be asyncronous, the problem is on the sleep.

Imagine I have a synchronous method that returns an Object. Annotating it with `@Retry` with a delay of 2 seconds will block the request thread for 2 seconds before calling my method again. My method finishes in milliseconds and doesn't do IO, so I don't need it to be async.  But that sleep call will always block the thread. 'd like the sleep to be run on another thread.

Sadly this is not possible in the example of a CDI bean returning Object from a method, since you don't have a way to stop the execution and returning to the original thread from there. But is possible to do in cases where the intercepted method already returns a CompletableFuture.

Now that's for CDI beans, where you don't even know whether you are on a request or not. Changing the return type there via an interceptor would cause ClassCastExceptions on the caller side.

But JAX-RS 2.1 added the possibility to return a CompletableFuture as an alternative to `@Suspended AsyncResponse`. When we are intercepting a JAX-RS method, and the return type is not a CompletableFuture, we mostly now that we are on the http thread and that the sleep we are about to do will block it. It is not possible to do right now, but my idea was to change the return type to a CompletableFuture just there in the interceptor, effectively freeing the request thread, making the sleep async and then going back to the original thread (which is where the user wanted the code to be executed) to process the request. This would apply only to JAX-RS resources as an implementation detail to avoid blocking the http thread.

So there are really 2 separated proposals. One for sleeping on another thread whenever possible (i.e.: when the intercepted method returns a CompletableFuture) and another one to go a step further on JAX-RS, which would probably need changes on the spec or propietary code, and for what I proposed the idea of changing the return type.

> I'm unsure whether it should be explicitly specified that when using @retry with a delay and @asynchronous together, the thread must be released when doing the delay as I think that would be tricky to verify.

Would be great to also have that clarified. It's basically inline with my proposal. Even if it's not possible to assert, at least saying "implementations are encouraged to do" would help.

**Comment by ggam** [comment]
Note that exceptions in CompletableFuture s are not being handled right now: #246.

**Comment by ggam** [comment]
Just to put another example on why `@Asynchronous` doesn't solve the case and why I think it's important to take advantage of the returned `CompletableFuture`: imagine my intercepted method is full of REST calls to other microservices. It's execution might be slow so I make all calls asynchronously calling `rx()` on the clients. My resource returns a CompletableFuture so JAX-RS 2.1 will handle everything for me.

Now a call to my method fails due to a `@Timeout`. The wasted time trying to make the calls to the other services is not a problem as it was done on another thread and so the HTTP thread has continued working on other requests. But now that `@Retry` annotation is going to sleep the HTTP thread for 1 second before calling my code again, that incidentally will run on another thread cause I took the care to make it non blocking.

That kind of situation is what I really have in mind. It's possible to end up with your whole server sleeping before retrying some failed methods, with your code being non blocking.

**Comment by Azquelt** [comment]
Ah, I think I see, you're asking for fault tolerance policies to be applied to the result of the method, rather than to the method call itself.

The expected flow with retries would be something like this?
1. User calls method
2. The method returns a CompletionStage (representing some async operation such as a JAX-RS client call)
3. Execution of the request continues
3. Some time later, the async operation fails
4. Fault Tolerance kicks in, and determines that a retry should occur
5. This causes the method to be called again
6. Let's say that this time the async operation completes successfully
7. The completion stage that was returned to the user completes (and all subsequent actions are run)

Currently, I don't think the spec covers anything other than applying fault tolerance policies around the method call itself. It sounds like that would need to be worked on, possibly under #246, before this request could be incorporated.

Tangentially, we could add a recommendation that implementations should not block a thread while delaying when using `@Asynchronous`.

**Comment by ggam** [comment]
> Ah, I think I see, you're asking for fault tolerance policies to be applied to the result of the method, rather than to the method call itself.

Yes, that's it. Actually, #246 asks for it. I just propose to take advantage of it and expand a bit further.

> Tangentially, we could add a recommendation that implementations should not block a thread while delaying when using @Asynchronous.

Yes. Currently, I don't see an option to change the pool that does the async invocation, but if such option exists, the pool that executes the delay should be different than the one specified by the user, to avoid locking application threads for runtime stuff.

As for the tests, I know it is fragile, but could they rely on log messages? If so, tests can set specific thread names and verify they are correctly called. The Java EE TCK uses that approach a lot :)

**Comment by Emily-Jiang** [comment]
You are talking about implementation details for the Fault Tolerance interceptor. The spec should just spec the behavior not force the implementor to implement in a particular way.

**Comment by Emily-Jiang** [comment]
will close this one for now. please reopen if you think this spec should do something in this area.
