### ISSUE TITLE
The spec shouldn't expect a single interceptor for all interceptor bindings

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-fault-tolerance#347]
The spec expects a single interceptor but defines multiple interceptor bindings, it would likely be easier and saner for users to define one interceptor per binding or just let the implementors do the way they want.

**Comment by Emily-Jiang** [comment]
> The spec expects a single interceptor but defines multiple interceptor bindings, it would likely be easier and saner for users to define one interceptor per binding or just let the implementors do the way they want.

- This feature is directly put forward by implementors to consolidate and operate on the same rules, so that microservices behaves the same among the different runtimes.

- This interceptor is for implementors to define. Specifying one interceptor allows the end users easily config the priority with a config property so that the sequence of interceptors is clear. 

- We don't want implementors to do their own thing: e.g. retry before timeout or timeout before retry. We want to enforce each retry should be bound with timeout. We walk through all interceptor bindings and clearly defined the invocation sequence. Giving big flexibility does not gain much but issues.

**Comment by rmannibucau** [comment]
> Specifying one interceptor allows the end users easily config the priority with a config property so that the sequence of interceptors is clear.

This does not change anything actually since the implementor can still change the priority programmatically in an extension.

However for end users it fully prevent to integrate with the interceptor chain which is bothersome when enriching the spec with custom features - leading to bypass the spec to speak transparently.

All you other points (which is to define the chain) is compatible with using interceptors so at the end this is an implementation detail and the vendor can couple the elements of the chain the way he wants: through interceptors or not.

Side note: if a spec defines the implementation in all details then it is not a spec but a library (with its impl) which is not how microprofile defined itself so probably saner to fix it just on a sanity point of view - ignoring the fact it breaks user usage.

**Comment by Azquelt** [comment]
Here's my argument for specifying that the implementation should be provided as a single interceptor:

1) While synchronous execution can be described fairly nicely as a series of interceptors, asynchronous execution cannot. The main problem is Timeout. When running asynchronously, we want Timeout to work even on methods which don't respond to being interrupted (e.g. methods which do blocking IO). This means:  
  
    * When Timeout is used on its own, when a timeout occurs, the TimeoutException should be thrown immediately, without waiting for the method to finish.  
  
    * When Timeout is used with Retry, if a timeout occurs, a new execution should be started after any configured delay, without waiting for the first one to finish.  
  
    * In addition, when Timeout is used with Bulkhead, if the timeout occurs while the execution is queued, the queued execution should be cancelled.  

    These interactions don't fit into the model of a chain of interceptors.
  
2) By specifying that the implementation should be provided as a single interceptor, we can also specify a way that the user can configure the priority of that interceptor in a standard way which will work on all implementations.
  
    Then, if they're using fault tolerance with other libraries which use interceptors, or have written their own, they can control where in the interceptor chain fault tolerance comes. This is important because:

    * Interceptors before FT in the chain will execute once for each call. For Asynchronous execution, they will run on the calling thread and won't have access to the result of the call because it hasn't yet completed.

    * Interceptors after FT in the chain may execute zero times (in the case of circuit breaker and bulkhead), once, or multiple times (in the case of retry). For Asynchronous execution, they will not run on the calling thread and will have access to the result of the call.

While I agree that we shouldn't be more specific than necessary, given that (1) prevents implementations from using individual interceptors, I think it makes sense to specify that a single interceptor must be used so that we can get the benefits of (2).

**Comment by rmannibucau** [comment]
@emily-jiang: interceptors define a chain and the priorities are defined this way (with jumps > 1) cause user must be able to plug himself in the chain. Fault tolerance breaks it and cdi programming model for no reason at all (you can impl it with plain interceptors). Since microprofike stated it must leverage cdi then it must enable the user to introduce custom interceptors in beyween fault tolerance features (useful for auditing, security, http integrations, ...).

Very worse case the spec shouldnt say how it is implemented but imho it should define the interceptor chain and not just one interceptor not interoperable with other libs or user code.

**Comment by OndrejM** [comment]
I have to agree with @rmannibucau and @struberg, here.

It surprised me today when I found out that the spec requires a single interceptor. This is an implementation detail for me, although I understand the reasons. I believe that all what we need could be reworded to specify the behavior without posing restrictions on the implementation.

For example:
* we could specify a default priority offset for all FT interceptors, by default set to 4010, with possibility to override this with a MP Config setting. This would work in the case of a single interceptor and also for multiple interceptors, which would add +1, +2, ... to the offset.
* we need to specify the interaction of individual annotations. If possible, we should specify the order in which they are chained. If the order doesn't work for all combinations, then we can specify exceptions. Implementors then can choose to have individual interceptors for each annotation, a single interceptor everything, or just some annotations combined into a single interceptor while still having more interceptors.

Implementors could also find it useful to have individual interceptors for synchronous methods, while a single interceptor for asynchronous methods. It makes no sense to force them to use a single interceptor for everything at all times.

**Comment by Emily-Jiang** [comment]
We discussed a bit more in today's meeting. The conclusion is that we will remove the mandate of one interceptor but just specifying the base order of the first interceptor. The logic calling order will remain unchanged. e.g. If you annotate with `@Retry` and `@Timeout`, `Timeout` will be applied to each retry.
