### ISSUE TITLE
Ensure interceptor(s) can be added without being in sources

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-fault-tolerance#348]
The idea is to fully read in the conf interceptor set up instead of requiring them to be in java sources which is kind of not the goal of a fault tolerant library.

Idea is to not have any import of the spec in the sources and add the instrumentation through configuration only (mp config). This enables to make an app fault tolerant depending where it is deployed and not hardcode some defaults which will likely be wrong in all cases.

**Comment by brunobat** [comment]
Hi Romain, thanks for your comment.
This looks like material for a spec with a broader scope.  This changes the way beans are loaded and it would potentially be also useful for other Microprofile Specs.

**Comment by rmannibucau** [comment]
Hi @brunobat 

Agree, for fault-tolerance and opentracing it can be key features.

**Comment by OndrejM** [comment]
I believe that this is already possible with MP Config, the app just needs to declare FT annotations. I don't think that supporting FT functionality just with external config is ideal, as it would be more complex to implement and adds a little value on top of the existing behavior.

A compromise solution would be to add one dummy annotation, that would trigger all FT interceptors but only if they are enabled with MP Config. So developers would just annotation a method e.g. with `@FaultTolerant` and later would enable FT features on the method with existing MP config settings.

Would that make sense?

**Comment by OndrejM** [comment]
Opentracing already supports this with a generic `@Traced` annotation.

**Comment by rmannibucau** [comment]
@OndrejM not sure I'm following, it is trivial to implement and we do it since some years in several libs so it is not about the implementation. The common use case is 1. I deploy my app 2. one remote service is unreliable 3. some config update, restart and we are good. With current approach you have to do 1. deploy 2. an issue appear 3. go back to dev 4. QA (potentially N > 1 layers) 5. prod which is really too costly (duration). Technically having an annotation or not does not change anything, checking MP-config or Annotated is pretty much the same (both are equivalent to checking a map with contains) so IMHO it is better to meet prod use cases than putting impl constraints first.

**Comment by Emily-Jiang** [comment]
I am not sure about the magic, which makes application is difficult to read. I have not got any real use case as yet. Please explain your use case. Do you want to use this for your production? We discussed this in the past and decided not to proceed with it unless there is a real use case to ask for this.

**Comment by rmannibucau** [comment]
I dont plan, I do since 6 years ;). All deployment concerns - and transversal features - are configured by deployment and not hardcoded. Means that some deployment will just not activate any retry, not even interceptor chain, but others will have ~10 interceptors (from security to auditing without forgetting resilience).

This enables to manage the deployments from local distro - electron like - to cloud deployments very smoothly and no code change.

**Comment by Azquelt** [comment]
We looked at this issue again on the call today and came to the conclusion that we don't want to add this feature to the spec for the following reasons:

1. With the way Fault Tolerance is designed, you have to know exactly where in the code you need to add the annotation. It's not like a service mesh where you can externally see when one service is calling another, you need to know the class and method where you would want the annotation added.

    If you need to know the code that deeply in order to provide the correct config, it seems more reasonable to update the code to add the annotation (even if you're just adding the annotation so it can be configured at deployment time)

2. If you really want this, you can write a CDI extension to add additional annotations where they don't exist in the code.

3. We're also concerned about making the code harder to debug as there's no indication in the code that any kind of extra fault tolerance logic could occur but at runtime anything could have been added.

For these reasons, I'm closing this issue but feel free to re-open it if you want to discuss further.

**Comment by rmannibucau** [comment]
Hi @Azquelt ,

I don't have the perms to reopen it but it is still a need I workaround with custom CDI extensions.

To answer your point:

1. this is true and compatible with this issue - actually it is the exact ask of this issue
2. I do but fault-tolerance is likely the thing you want to add on top of an application (+library) and not hardcode at all
3. This is CDI model and Microprofile is based on CDI so it must embrace it anyway. Note that it is *trivial* to debug using extensions and this is the way CDI dev are used to work.

I'd add that fault-tolerance already have meta-configuration to just adding an entry to bind the configuration on a method is trivial and really worth it in terms of use case.

For these reasons I'm gently asking you to reopen the issue to fix it.

**Comment by Azquelt** [comment]
On point 1 I'd refer to what I wrote above:
> If you need to know the code that deeply in order to provide the correct config, it seems more reasonable to update the code to add the annotation (even if you're just adding the annotation so it can be configured at deployment time)

Although I can see that you still want the feature despite the drawbacks, I think this severely limits the number of people who will find this feature useful.

For point 2: I disagree. While fault tolerance as a concept might be something you want to add around your application, MicroProfile Fault Tolerance is really about giving you the APIs to add it to your application easily.

There are other solutions (e.g. Istio) which have taken the approach of wrapping fault tolerance around your application rather than embedding it inside it.

For point 3: I completely disagree. When your code says it does one thing but actually does something else, it's much harder to track down problems.

Lastly, I disagree with your assertion that adding this is trivial, at least in a way that performs well. I wouldn't want to add anything to the spec that would require an implementer to create an extension which observes `ProcessAnnotatedType<?>` or `ProcessBean<?>` without any qualifiers as this would mean that it would need to load all classes in the application at startup. For small applications this might be acceptable but for large applications or applications which include a lot of libraries it is not.

**Comment by rmannibucau** [comment]
@Azquelt for point 1 it is simple: you sometimes just don't have the perm to touch the deliverable (from it being a war to a docker image) so using MP-config to add fault-tolerance is required in such cases. For point 2, the point is that adding such a feature is trivial and worth it, Istio does not match the same thing at all so it makes sense to have it in MP. Finally for point 3 I would agree with you if you drop MP-config support completely, if not then it is not worse.

Lastly I want you to think about your last paragraph, this is already the case if the implementation respects CDI - as required by the spec - so it is not a point ;).

**Comment by Azquelt** [comment]
Ok, here's some more detail on that last paragraph:

For parts of CDI, you can get away with not fully loading the class until it's needed by reading the class bytecode directly to determine the class name, methods and annotations. This way, if you have `ProcessAnnotatedType<MyClass>`, you only need to load `MyClass`. Similarly if you have `@WithAnnotations(Retry.class) ProcessAnnotatedType<?>`, you only need to load the classes which have a `@Retry` annotation on them somewhere.

If you have a beans.xml which declares that all classes should be considered as beans, then you don't really gain anything since you're probably going to have to load every class anyway, but if the majority of your application and library classes are not beans and are not needed for processing by a `ProcessAnnoatedType<>` event, you can save a lot of work at startup.

Weld presents an SPI for plugging in this sort of functionality: https://docs.jboss.org/weld/reference/latest/en-US/html/ri-spi.html#classFileServices If you want to know more, it's probably worth a look at that SPI and possibly a poke through the code to see how it's used.

**Comment by rmannibucau** [comment]
@Azquelt I know but this is not really true from a spec point of view, this is an optimization of some impl. Concretely, this violates CDI programming model since an extension can add @Retry through an annotation and it must be supported by MP so you don't really have the choice if you want to be CDI compliant. Also the beans.xml will never define all the beans since you only define interceptors/decorators/... but not actual business beans. The side note there is that MP-config already process injection points and that CDI container must throw events by spec so you don't save much at runtime.

**Comment by Ladicek** [comment]
My personal opinion is that adding fault tolerance policies to code that has possibly never been designed with them in mind can easily be dangerous. We shouldn't make it too easy to shoot yourself in the foot.

(Specifically, I think that for retry, the method in question should be idempotent. For timeout, it should respect interrupts. For circuit breaker and bulkhead, the callers can receive exceptions they are not prepared to handle. Fallback is probably safe, but that requires adding code anyway.)

**Comment by rmannibucau** [comment]
This is however what we do with proxies and gateway.

**Comment by Ladicek** [comment]
That's on a somewhat different level, though. For example, assuming

**Comment by rmannibucau** [comment]
It does cause it depends where you put it. Typically it only makes sense on anything else than bounds/layers so it is the same architecturally speaking, just colocalized or not IMHO

**Comment by Emily-Jiang** [comment]
@rmannibucau I still think this magic is quite difficult to debug and open up for more questions. We again today in our hangout and discussed again and agreed not to do it. 
If you want to enable Fault Tolerance, you could use Istio to add the magic. 
We are going to close this issue.

**Comment by rmannibucau** [comment]
@Emily-Jiang for the record: this issue was only about ensuring there is a standard built-in configuration convention. The feature by itself is already provided by CDI for any CDI compatible implementation.
