### ISSUE TITLE
ft.<name>.bulkhead.executionDuration metrics shouldn't be linked to bulkhead

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-fault-tolerance#354]
The method execution duration is unrelated to bulkhead so why is it linked in this metric?

**Comment by Azquelt** [comment]
The rationale was that although it's not directly related to bulkhead, it's one of the metrics that's important if you're trying to understand why your bulkhead is or isn't being hit.

E.g. if your bulkhead is filling up, it's probably because you are getting a lot of requests, or because they're taking a long time, so having executionDuration as a metric allows you to see which case is happening.

Therefore, we decided that whenever a bulkhead is used, the executionDuration metric would be useful and so should be added.

**Comment by rmannibucau** [comment]
@Azquelt I can understand that but shouldnt it be added to the "chain" (without any annotation) too for consistency and comparison of the numbers? Also the description can need to be refined in such a case.

**Comment by rmannibucau** [comment]
Current one is (in metrics.adoc)

    Histogram of method execution times. This does not include any time spent waiting in the bulkhead queue.

What about

    The time the permit or a thread of the pool of the bulkhead is actively hold.

**Comment by Azquelt** [comment]
Ah ok, I see where you're going.

I'd prefer to keep the fact that it's a histogram in the description. How about this?

>Histogram of the time that executions spend holding a semaphore permit or using one of the threads from the thread pool.

Alternatively, we could be more verbose:

>Histogram of the execution times. For synchronous execution, this is the time that the execution holds a semaphore permit. For asynchronous execution, this is the time that the execution is using one of the threads from the thread pool.

On balance, I think I prefer the first version.

**Comment by rmannibucau** [comment]
+1 for the first version
