### ISSUE TITLE
review inheritance

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-fault-tolerance#359]
There are some tck testing the inheritance rules (like RetryVisibilityTest) but it makes the user life impossible cause it is not aligned on CDI model and relies on reflection only.

This task is about ensure the spec 100% align on CDI and does not try to define rules against CDI.

**Comment by Azquelt** [comment]
Can you be more specific about which tests are wrong and which parts of the CDI spec they're in conflict with?

**Comment by rmannibucau** [comment]
The main issue is to take into consideration the parent method only if the method does not exist in current class, if the parent method exists it should override the class definiton in any case. Method always being more specific than the class.

Same as the class config can be overriden by an annotation on the class, the same applies on the method so reading the method config - whatever it comes from the subclass or the parent - THEN the class level metadata is saner IMHO and aligned on CDI Annotated model.

RetryVisibilityTest shows the weirdness of the rules.

**Comment by Azquelt** [comment]
Ok, I'll have a look further into this.

**Comment by Azquelt** [comment]
I've reviewed all the tests in `RetryVisibilityTest` and compared the test expectations against CDI 2.0 Chapter 4 and Common Annotations 1.3 section 2.1.

The only test that appeared questionable to me was `serviceOverrideClassLevelUsesClassLevelAnnotation`, however, on closer inspection the behaviour of this test matches the behaviour of interceptor bindings in general (as least when using Weld).

In particular, when a class and its subclass have the same binding annotation but with different parameters, the binding on the subclass is used when resolving interceptors, even when calling a method from the superclass which isn't overridden in the subclass.

**Comment by rmannibucau** [comment]
Hmm, in owb which passes cdi 2.0 tck, the inheritance rule are not natural, can be cause annotatedmethod model is a bit different but also means there is a gap in cdi and MP does not look natural for half of users. Do you think we can find a model natural for both user communities? This is quite painful compared to normal behavior since cdi 1.0.

**Comment by rmannibucau** [comment]
I didnt test the same impl but i hit it passing mp-ft tcks on owb and got surprised to not have the behavior i was expecting and to be force to manage inheritance in my extension.

If uncovered by cdi - or 2 impl out there - this can lead to some unportable behavior for mp and the tck to drop (idea being to rely on cdi and not let the user be surprised to have 2 set of rules for the same technical thing).

**Comment by Azquelt** [comment]
I'm going to put the small test app on my github so @rmannibucau and @brunobat can see it.

**Comment by Azquelt** [comment]
Test app here: https://github.com/Azquelt/inherited-interceptor-example

@rmannibucau @brunobat

**Comment by Emily-Jiang** [comment]
Your bean1A has both service2 and service3 defined. Method level annotation overrides the class level. Hence, service2 has InterceptorB for Bean1A as it inherits the class-level annotation. What is the issue here then? I think what @Azquelt is trying to say that the inherited methods use the subclass's class-level annotation instead of parent class.

I reread the annotation spec. it says
The interplay of annotations and inheritance in the Java language is potentially a source 
of complexity for developers. Developers will rely on some implicit assumptions when 
figuring out how annotations compose with other language features. At the same time, annotation semantics are defined by individual specifications, hence the potential for inconsistencies to arise.

The only inconsistent scenario is 👍 
```
@TransactionAttribute(REQUIRED)
class Base {
@TransactionAttribute(NEVER)
public void foo() {...}
public void bar() {...}
}
@Stateless
@TransactionAttribute(REQUIRES_NEW)
public class EBean extends Base {
}

```
According to the Annotation spec, you should get:
foo() in EBean TransactionAttribute(NEVER) (From Base class)
bar() in EBean TransactionAttribute(REQUIRED)(from Base class)

In Weld, it seems it will give you
foo() in EBean TransactionAttribute(REQUIRED_NEW) 
bar() in EBean TransactionAttribute(REQUIRED_NEW)
We need to try it out on OWB. @brunobat did you get a chance to try?

**Comment by rmannibucau** [comment]
Issue is that the spec uses class level intercepyor instead of parent method one when defined. This is not the behavior we - owb, tomee, meecrowave, .... all owb based servers actually - have for years so this is very misleading.

If someone can run the same test than in my patch with weld we could compare it more accurately and check if TCKs are wrong but currently they dont match owb impl which passes TCKs so either it is a shadow area and MP tck should ignore it or MP should rely on where it runs (MP depending on another spec defining it this is not to MP to test it).

Note that what you described for bar is ok but not for foo which easily leads to either something complex to override (if you have > 3-4 methods) or inconsistent compared to the code.

**Comment by Azquelt** [comment]
Results for Weld are identical:
```
Bean1.class > service + InterceptorA
Bean1A.class > service + InterceptorB
Bean1.method inherited > service2 + InterceptorA
Bean1A.method inherited > service2 + InterceptorB
Bean1.method overriden > service3 + InterceptorB
Bean1A.method overriden > service3 + InterceptorA
```

As far as I'm aware, this **exactly matches** the expected behaviour of the MP TCK tests.

`Bean1A.method inherited` shows that both Weld and OWB use the annotation from the subclass when the subclass has an overriding method with no annotation.

This is the same setup as `serviceBaseROCMOverridedClassLevelMethodOverride()` which uses the bean `RetryOnClassAndMethodServiceOverrideClassLevelMethodOverride`.

`Bean1.method overriden` shows that both Weld and OWB use the annotation from the overriding method when the subclass has an overriding method with an annotation.

This exact case is not tested in the MP TCK. The most similar one is probably `serviceBaseROMOverridedMethodLevel` which uses the bean `RetryOnMethodServiceOverridedMethodLevel` which shows that when an overriding method is annotated, the annotation from the overriding method is used.

If you still think there's a problem, could you please point out the specific test method that you have an issue with.

**Comment by rmannibucau** [comment]
Hmm, seems it changed a bit between 1.0 and 1.1 so I guess I can have hit that before and master can be fine. Ok for me to close it since we validated - thanks - weld and owb are aligned and we can rely on that. We would reopen it if we hit it again with > 1.1.x

**Comment by Azquelt** [comment]
Sounds good, thanks
