### ISSUE TITLE
Behaviour of methods returning CompletionStage with and without @Asynchronous 

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-fault-tolerance#368]
It is not clear what's the difference, in the expected behavior, when returning a CompletableFuture from a method annotated with `@Asynchronous` and from a method without that annotation. 
Examples:
```   
    import org.eclipse.microprofile.faulttolerance.Asynchronous;

    @Asynchronous
    public CompletionStage<String> serviceA() {
        CompletableFuture<String> future = new CompletableFuture<>();
        ...
        return future;
    }
```

``` 
    public CompletionStage<String> serviceA() {
        CompletableFuture<String> future = new CompletableFuture<>();
        ...
        return future;
    }
```

This is especially important when we are using the `@Retry` annotation in the methods.
What will happen when a retry is performed in both serviceA() and serviceB()?

**Comment by Azquelt** [comment]
I think the use case we're attempting to solve is that we want to apply fault tolerance logic over an API which is already asynchronous (e.g. a JAX-RS client call, or a mongodb async call).

E.g. we might make a REST service which calls two other services in parallel and then returns their results. This could be done asynchronously like this:
```
@GET
public CompletionStage<MyResult> serviceCall() {
    CompletionStage<AResult> csA = serviceA.call();
    CompletionStage<AResult> csB = serviceB.call();

    CompletionStage<MyResult> result = new CompletableFuture.completedFuture(new MyResult())
        .thenCombine(csA, (result, a) -> result.add(a))
        .thenCombine(csB, (result, b) -> result.add(b));

    return result;
}
```

`ServiceA.call()` might look like this:
```
public CompletionStage<AResult> call() {
    return myWebTarget.request().rx().get(AResult.class);
}
```

We want to be able to apply Fault Tolerance annotations to `serviceA.call()` and serviceB.call()` to apply fault tolerance logic around the CompletionStage returned from those methods.

All of the above code runs very quickly and returns a CompletionStage to JAX-RS way before the requests to serviceA or serviceB have actually finished, so if `@Retry` was used, any retry attempt would need to be run asychronously.

If any retry attempts will be run asynchronously, I think it makes sense to also run the initial attempt asynchronously to avoid the case where the user may have written code which relies on some thread context that isn't available when running asynchronously (e.g. calling a `RequestScoped` CDI bean).

So, given that Retry must run Asynchronously, I think one of the following options makes sense:
* Methods with any Fault Tolerance annotation which return CompletionStage always run asynchronously, regardless of whether `@Asynchronous` is used
* Methods with the `@Retry` annotation which return CompletionStage always run asynchronously, regardless of whether `@Asynchronous` is used
* Methods with any Fault Tolerance annotation which return CompletionStage must be annotated with `@Asynchronous`, otherwise you get a deployment time exception
* Methods with with the `@Retry` annotation which return CompletionStage must be annotated with `@Asynchronous`, otherwise you get a deployment time exception

**Comment by brunobat** [comment]
From the options you mention I think what makes the code less ambiguous is:
* Methods with any Fault Tolerance annotation which return CompletionStage must be annotated with @Asynchronous, otherwise you get a deployment time exception

This will cover the case for the usage of `@Asynchronous` with `@retry` and would inform the user that he should not expect a synchronous behavior from that call, thus preventing the misuse of thread local

**Comment by Emily-Jiang** [comment]
hmmm. This will break existing application though as we don't prevent the usage of CompletionStage. I think we should discuss a bit more later.

Maybe any methods with `Retry` used for the method of returning CompletionStage should run asynchronously anyway, which has less impact and customer might not notice anything but their retry is attempted.

**Comment by Emily-Jiang** [comment]
Method without `@Asynchronous` annotation returning CompletionStage will not be retried even if `Retry` annotation is specified and the completionStage is completed exceptionally, which is the previous behaviour.

``
@Retry
public CompletionStage<String> serviceA() {
        CompletableFuture<String> future = new CompletableFuture<>();
        ...
        return future;
    }

In the above method, the serviceA returned exceptionally will not be retried.

**Comment by Emily-Jiang** [comment]
@brunobat @carlosdlr @Azquelt agreed the above statement on 19th Dec.
