### ISSUE TITLE
Create Fallback functionality

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#4]
When an invocation fails, provide the ability to fallback to another invocation that may be more reliable not necessarily the full need.

**Comment by Emily-Jiang** [comment]
Please have a look at the above commit a479883 to see whether this meets your expectation.

**Comment by mkouba** [comment]
The spec should be more clear on the lifecycle and requirements of a `FallbackHandler` implementation, i.e. a new instance of handler is created for each fallback invocation?

**Comment by johnament** [comment]
I don't see the interface mentioned in the spec.

**Comment by mkouba** [comment]
It's part of the API, see `org.eclipse.microprofile.fault.tolerance.inject.Fallback.handler()`. Not sure what the spec actually means in MP.

**Comment by johnament** [comment]
Oh, I think I know what you mean.  Are you expecting that the handler is a CDI bean?

**Comment by mkouba** [comment]
Well, I'm not expecting anythig... just saying that it's undefined ;-). The truth is that using POJO is a bit limiting and using CDI bean might be more powerful... but I have no idea how to define this. Hm, maybe `@Fallback` could be a qualifier and the first matching `FallbackHandler` bean could be used? I'm not sure.

**Comment by Emily-Jiang** [comment]
@mkouba just to confirm: The fallback class should be unmanaged. A new instance should be created for each fallback. Will document this in the javadoc. The usage:
@Fallback(handler=MyFallback.class) or we could even simplify as
@Fallback(MayFallback.class)

In this way, it is much easier to implement and also I have not seen the use cases where need to inject the fallback and want the same instance of the fallback is used. The fallback class is pretty much stateless. 
As for your idea of the first matching FallbackHandler bean could be used, it will easily run into non-portable behaviour or random behaviour though, as we cannot control which one will be used for fallback on.

**Comment by johnament** [comment]
I would prefer to see these as CDI managed.  If there's no scope then they're not beans, but if they're `@Dependent` then a new one per invocation.

**Comment by mkouba** [comment]
Well, I was thinking about something like this:
```java
class MyService {
  @Inject
  OtherService otherService;
  
  @Timeout(3000)
  @Fallback // If handler not set then lookup bean of type FallbackHandler<Long> and qualifier @FallbackFor(MyService.class)
  Long getAmount() {
    return otherService.getAmount() * 2;
  }

  // The fallback bean should be dependent
  // We can detect unsatisfied and ambiguous handlers
  @Produces
  @FallbackFor(MyService.class)
  FallbackHandler<Long> myFallback() {
    return (ctx) -> 42; // If FallbackHandler is @FunctionalInterface
  }
}
```
And the producer could inject other beans if needed.

The other problem of the current approach is type-safety - you can specify a handler class which is not usable.

**Comment by Emily-Jiang** [comment]
The implementation must validate the fallback class to be a super class of FallbackHandler though, which is to solve the type-safety. In your approach, how can you cope with the scenario of two methods defined in MyService, both of which specify Fallback?

**Comment by mkouba** [comment]
> The implementation must validate the fallback class to be a super class of FallbackHandler though..

Is it defined anywhere? Also what if you specify `FallbackHandler<Long>` and the method would return `String`? Could be probably checked during bootstrap. The same applies to my approach. If more than one eligible beans exist (very easy check) -> a problem during bootstrap.

> how can you cope with the scenario of two methods defined in MyService, both of which specify Fallback?

Each method receives its own handler instance (it's `@Dependent`).

**Comment by Emily-Jiang** [comment]
You were right. I missed it in the javadoc. 
>>Each method receives its own handler instance (it's @Dependent).
What if the method have different return type?

**Comment by mkouba** [comment]
> What if the methods have different return type?

Good point. You could just create multiple producers (would work due to type-safe resolution). But it's not really nice. Maybe we could replace `@FallbackFor(MyService.class)` with some string-based id, e.g. you would have to use something like `@Fallback("amount")` on both sides the "protected" method and the producer method... just throwing up ideas.

**Comment by Emily-Jiang** [comment]
ok. This is what I think with the current model:
```
class MyService {
  @Inject
  OtherService otherService;
  
  @Timeout(3000)
  @Fallback(MyFallbackService.class) 
  Long getAmount() {
    return otherService.getAmount() * 2;
  }

  // The fallback bean should be dependent
  // We can detect unsatisfied and ambiguous handlers
  public class MyFallback extends FallbackHandler<Long>
  Long handle(ExecutionContext context) {
    return 42;
  }
  }
}
```
The Fallback has the method signature to force the value to be type of FallbackHandler. As for the type argument, the implementation can validate it without much issues. In this way, it solves the type safety and it is very easy to be used.

**Comment by mkouba** [comment]
@Emily-Jiang I understand the current proposal. However, the fallback instance is not supposed to be a bean instance, or? So that you cannot inject anything in the fallback. In simple cases, this would fine. But a more powerful option may be useful.

There are many possibilities. We can for example say that a fallback producer methid name must be methodName + `Fallback`, e.g. in our case, we're looking for a bean of type `FallbackHandler<Long>` and qualifier that is derived from the method name - `getAmount() -> getAmountFallback()`:

```java
class MyService {
  @Inject
  OtherService otherService;
  
  @Timeout(3000)
  @Fallback
  Long getAmount() {
    return otherService.getAmount() * 2;
  }

  @Produces // a special qualifier will be added automatically - @FallbackFor("getAmount")
  FallbackHandler<Long> getAmountFallback() {
    return (ctx) -> 42;
  }
}
```

**Comment by Emily-Jiang** [comment]
>However, the fallback instance is not supposed to be a bean instance, or? So that you cannot inject anything in the fallback. In simple cases, this would fine. But a more powerful option may be useful.

The fallback class is a bean class and it does support injection. We only want it to be unmanaged. This class should be treated similar as JavaEE component classes e.g. servlet class etc.

**Comment by mkouba** [comment]
@Emily-Jiang Well, you're probably referencing to `The instance is unmanaged` in `Fallback.value()` javadoc. I don't think the wording is very clear. It should be probably something like:

> The handler instance used by the container to service a fallback invocation is a non-contextual
instance created using the CDI SPI. The instance exists to service a single invocation only.

Plus we should also mention the validation (to ensure type-safety).

If we go this way then the only differences are (compared to https://github.com/eclipse/microprofile-fault-tolerance/issues/4#issuecomment-308636257):
- new class VS new producer method (probably does not matter from user POV)
- fallback handler cannot be reused (not a big deal since it can inject a shared component)

**Comment by Emily-Jiang** [comment]
@mkouba thanks for your suggestions. I'll fix the javadoc as you suggested. I agree the two approaches are quite similar. In your solution, forcing to name the method as methodName + Fallback can be error-prone. In the current approach, the handler class can be used by multiple methods if their return type is the same.

**Comment by Emily-Jiang** [comment]
I was made aware of one more use case for the fallback. 
Some developers might want put the fallback method on the same class as the origin method. e..g
public class myBean{
private String a;
public void callMyService(){

//use a;
}
priviate void myFallback() {
//use a;
}
}

In our current approach, we cannot do it. In order to achieve this, we need to add one more method on the fallback annotation to take in the fallback method name. Thought?
}

**Comment by mkouba** [comment]
@Emily-Jiang That's the reason why I proposed a more powerful approach in https://github.com/eclipse/microprofile-fault-tolerance/issues/4#issuecomment-308636257. I'm not sure it's 100% feasible though. 

It could work like this (consider the use case described in my comment):
1. first try to find a bean with `FallbackHandler<Long>` and qualifier `@Fallback("getAmount")`
2. then try to find a bean with `FallbackHandler<Long>` and qualifier `@Default` (reusable handler)
3. if no handler bean is found, fail with exception

The `@Fallback` value could be even a regular expression. 

Note that the guarded method would also declare `@Fallback` annotation but the value would be just ignored there.

Also note that the handler could be defined as a managed bean or producer method.

**Comment by Emily-Jiang** [comment]
@mkouba This approach still cannot deal with the scenario where I want to fallback to a method on the same instance as the original method. Am I misunderstanding you?

**Comment by mkouba** [comment]
Well, you could define a producer method on the same bean class and if the bean scope is a normal scope "broader" than the fallback invocation (e.g. `@ApplicationScoped`) it should work.

**Comment by Emily-Jiang** [comment]
I see. There are a lot of hoops to jump. If we directly define another method on Fallback. This should clearly easily solve the issue. See my PR as follows.

**Comment by johnament** [comment]
I think we'd be mixing concerns having the fallback method on the actual impl.  Why can't this be on a separate class?

**Comment by Emily-Jiang** [comment]
The reason is that the fallback method might want to share some instance variables as the origin method.
