### ISSUE TITLE
Improve MP FT metrics using Metrics tags

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#401]
With the new functionality of Metrics 2.0 with multiple tag support, this massively simplifies the metrics name, which makes metrics query creation much easier.
We need to revisit our metrics name to see whether we can simplify the names.

**Comment by pilhuhn** [comment]
e.g.   `ft.<name>.invocations.failed.total` ->  `ft.invocations{method=<name>, kind=<failed|good|..>}`

**Comment by Emily-Jiang** [comment]
In today's hangout call with @donbourne @pilhuhn
We agreed on the following metric name

- Invocation
ft.<name>.invocations.failed.total` ->  `ft.invocations.total{method=<name>, kind=<failed|good|..>}` 

- Retry

 ft.retry.total{method = <method name>, kind=(succeededNotRetried | succeededRetries | callsFailed|) }

[Query examples](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/rest-endpoints.adoc#openmetrics-format )
we need to add  a couple of paragraphs to mention the query name from 
[metrics spec](https://prometheus.io/docs/prometheus/latest/querying/examples/ )

**Comment by donbourne** [comment]
I'd suggest being specific (rather than general) on your label names.  "kind" might better be called "result" in the Invocation metrics.

**Comment by Azquelt** [comment]
I think the best approach is to keep roughly the metrics that we have, but collapse several metrics into one where that makes sense.

Here's what that would look like:

## Overall Metrics

Old:
* `ft.<name>.invocations.total`
* `ft.<name>.invocations.failed.total`

New:
* `ft.invocations.total{method=<name>, result=[success|failure]}`

## Retry Metrics

Old:
* `ft.<name>.retry.callsSucceededNotRetried.total`
* `ft.<name>.retry.callsSucceededRetried.total`
* `ft.<name>.retry.callsFailed.total`
* `ft.<name>.retry.retries.total`

New:
* `ft.retry.calls.total{method=<name>, result=[succeededNotRetried|succeededRetried|failed]}`
* `ft.retry.retries.total{method=<name>}`

## Timeout Metrics

Old:
* `ft.<name>.timeout.executionDuration`
* `ft.<name>.timeout.callsTimedOut.total`
* `ft.<name>.timeout.callsNotTimedOut.total`

New:
* `ft.timeout.executionDuration{method=<name>}`
* `ft.timeout.calls.total{method=<name>, timedOut=[true|false]}`

## Circuit Breaker Metrics

Old:
* `ft.<name>.circuitbreaker.callsSucceeded.total`
* `ft.<name>.circuitbreaker.callsFailed.total`
* `ft.<name>.circuitbreaker.callsPrevented.total`
* `ft.<name>.circuitbreaker.open.total`
* `ft.<name>.circuitbreaker.halfOpen.total`
* `ft.<name>.circuitbreaker.closed.total`
* `ft.<name>.circuitbreaker.opened.total`

New:
* `ft.circuitbreaker.calls.total{method=<name>, result=[success|failure|prevented]}`
* `ft.circuitbreaker.state.total{method=<name>, state=[open|halfOpen|closed]}`
* `ft.circuitbreaker.opened.total{method=<name>}`

## Bulkhead Metrics

Old:
* `ft.<name>.bulkhead.concurrentExecutions`
* `ft.<name>.bulkhead.callsAccepted.total`
* `ft.<name>.bulkhead.callsRejected.total`
* `ft.<name>.bulkhead.executionDuration`
* `ft.<name>.bulkhead.waitingQueue.population`
* `ft.<name>.bulkhead.waiting.duration`

New:
* `ft.bulkhead.concurrentExecutions{method=<name>}`
* `ft.bulkhead.calls.total{method=<name>, result=[accepted, rejected]}`
* `ft.bulkhead.executionDuration{method=<name>}`
* `ft.bulkhead.waitingQueue.population{method=<name>}`
* `ft.bulkhead.waiting.duration{method=<name>}`

## Fallback metrics

Old:
* `ft.<name>.fallback.calls.total`

New:
* `ft.fallback.calls.total{method=<name>, result=[applied|skipped]}`

## Queries

As requested on the call last week, here is a selection of queries which can be run against these metrics.

I've taken the queries from my Fault Tolerance 1.1 dashboard, and then shown how they would be rewritten to use the new metrics.

### Overall Queries

#### Invocations [per second, avg t]

Old: `rate(application:ft_[[method]]_invocations_total[$avg_period])`
New: `sum(rate(application:ft.invocations.total{method="$method"}[$avg_period]))`

#### Failure rate [%, avg t]

Old:
```
rate(application:ft_[[method]]_invocations_failed_total[$avg_period]) * 100
 / 
rate(application:ft_[[method]]_invocations_total[$avg_period])
```

New:
```
sum(rate(application:ft_invocations_total[$avg_period]{method="$method", result="failure"})) * 100
 / 
sum(rate(application:ft_invocations_total[$avg_period]{method="$method"}))
```


### Retry Queries

#### Retries per invocations [avg t]

Old:
```
rate(application:ft_[[method]]_retry_retries_total[$avg_period])
 / 
(
   rate(application:ft_[[method]]_retry_calls_succeeded_not_retried_total[$avg_period])
 + rate(application:ft_[[method]]_retry_calls_succeeded_retried_total[$avg_period])
 + rate(application:ft_[[method]]_retry_calls_failed_total[$avg_period])
)
```

New:
```
sum(rate(application:ft.retry.retries.total{method="$method"}[$avg_period]))
/
sum(rate(application:ft.retry.calls.total{method="$method"}[$avg_period]))
```

#### Calls failing despite retries [%, avg t]

New:
```
sum(rate(application:ft.retry.calls.total{method="$method", result="failed"}[$avg_period]))
/
sum(rate(application:ft.retry.calls.total{method="$method"}[$avg_period]))
```

### Timeout Queries

#### Execution duration [s] (Histogram)

Old: `application:ft_[[method]]_timeout_execution_duration_seconds`
New: `application:ft_timeout_execution_duration_seconds{method="$method"}`

#### Invocations Timed Out [%, avg t]

Old:
```
rate(application:ft_[[method]]_timeout_calls_timed_out_total[$avg_period]) * 100
/
(
  rate(application:ft_[[method]]_timeout_calls_timed_out_total[$avg_period])
+ rate(application:ft_[[method]]_timeout_calls_not_timed_out_total[$avg_period])
)
```

New:
```
sum(rate(application:ft_timeout_calls_total{method="$method", timedOut="true"}[$avg_period])) * 100
/
sum(rate(application:ft_timeout_calls_total{method="$method"}[$avg_period]))
```

### Circuit Breaker Queries

#### Circuit Breaker State

Old (three queries drawn on the same graph):
```
A: irate(application:ft_[[method]]_circuitbreaker_open_total_seconds[1m])
B: irate(application:ft_[[method]]_circuitbreaker_half_open_total_seconds[1m])
C: irate(application:ft_[[method]]_circuitbreaker_closed_total_seconds[1m])
```

New:
```
irate(application:ft_circuitbreaker_state_total_seconds{method="$method"}[1m])
```

#### Circuit Breaker Run but Failed [%, avg t]

Old:
```
irate(application:ft_[[method]]_circuitbreaker_calls_failed_total[$avg_period]) * 100
 / 
(
   irate(application:ft_[[method]]_circuitbreaker_calls_failed_total[$avg_period])
 + irate(application:ft_[[method]]_circuitbreaker_calls_succeeded_total[$avg_period])
)
```

New:
```
sum(irate(application:ft_circuitbreaker_calls_total{method="$method", result="failure"}))
/
sum(irate(application:ft_circuitbreaker_calls_total{method="$method", result=~"success|failure"}))
```

### Bulkhead Queries

#### Bulkhead Average Concurrent Calls (estimated number of concurrent calls without the bulkhead)

Old:
```
(
   rate(application:ft_[[method]]_bulkhead_calls_rejected_total[1m])
 + rate(application:ft_[[method]]_bulkhead_calls_accepted_total[1m])
)
 *
application:ft_[[method]]_bulkhead_execution_duration_mean_seconds
```

New:
```
sum(rate(application:ft_bulkhead_calls_total{method="$method"}[1m]))
*
sum(application:ft_bulkhead_execution_duration_mean_seconds{method="$method"})
```

#### Bulkhead Execution Time [s] (Histogram)

Old: `application:ft_[[method]]_bulkhead_execution_duration_seconds`
New: `application:ft_bulkhead_execution_duration_seconds{method="$method"}`

#### Bulkhead Rejected Calls [%, avg t]

Old:
```
rate(application:ft_[[method]]_bulkhead_calls_rejected_total[$avg_period]) * 100
 / 
(
   rate(application:ft_[[method]]_bulkhead_calls_rejected_total[$avg_period])
 + rate(application:ft_[[method]]_bulkhead_calls_accepted_total[$avg_period])
)
```

New:
```
sum(rate(application:ft_bulkhead_calls_total{method="$method", result="rejected"}[$avg_period]))
/
sum(rate(application:ft_bulkhead_calls_total{method="$method"}[$avg_period]))
```

### Fallback Queries

#### Fallback Rate [%, avg t]

Old:
```
rate(application:ft_[[method]]_fallback_calls_total[$avg_period]) * 100
/
rate(application:ft_[[method]]_invocations_total[$avg_period])
```

New:
```
sum(rate(application:ft_fallback_calls_total{method="$method", result="applied"}[$avg_period])) * 100
/
sum(rate(application:ft_fallback_calls_total{method="$method"}[$avg_period]))
```

**Comment by Azquelt** [comment]
There are a few areas we could tweak these metrics:

### Success criteria

Both `Retry` and `CircuitBreaker` have a `result` tag which indicates whether it's counting invocations that "succeeded" or "failed". However, for each policy, what counts as a "success" or "failure"?

This has generally become more difficult to discern since FT 2.1 with the addition of `applyOn` and `skipOn` to `@CircuitBreaker` and `@Fallback`, in addition to the existing `retryOn` and `abortOn` of `@Retry`.

#### Success for overall metrics

This is the simplest metric. `ft.<name>.invocations.failed.total` is incremented if an exception is thrown to the caller after all FT processing is complete.

Therefore for the new metric:
* value returned -> success
* exception thrown -> failure

#### Success for CircuitBreaker

This is probably the next easiest one, since the definition of `CircuitBreaker` requires the success and failure criteria to be defined as they're used to determine when the breaker opens and closes. The spec outlines the following rules:
* value returned = `success`
* exception thrown that matches `skipOn` = `success`
* exception thrown that matches `applyOn` = `failure`
* anything else = `success`

Therefore, I think the current tag of `result=success|failure|prevented` makes sense.

#### Success for Retry

We don't define "success" or "failure" for `@Retry` in the spec, we just say how to determine whether a given result _should be retried or not_.

We define these rules:
* value returned -> return the value
* exception thrown matching `abortOn` -> rethrow that exception
* exception thrown matching `retryOn` -> retry the execution
* exception thrown not matching a previous rule -> rethrow the exception

We currently have three result categories: `succeededNotRetried`, `succeededRetried` and `failed`. The relevant spec [Metrics added for `@Retry`][retry-metrics] doesn't define what "succeeded" or "failed" mean. The TCK asserts that a returned value counts as a success and a thrown exception matching `retryOn` counts as a failure.

I'd suggest we do one of the following:

1. Define "success" and "failure" in the spec in a way that's consistent with `@CircuitBreaker`
2. Redesign the `@Retry` metrics to be clearer by avoiding reference to "success" or "failure"

[retry-metrics]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#_metrics_added_for_code_retry_code

### Fallback Metrics

`@Fallback` is the only policy which is applied outside of `@Retry`, and so is guaranteed to be used only once per invocation.

We could therefore integrate the fallback metrics with the overall metrics and have something like this:
```
ft.invocations.total{method=<name>, result=[success|failure|fallback]}
```
Where `fallback` indicates that the method threw an exception which resulted in the fallback being invoked. This makes the assumption that the fallback itself did not throw an exception, so we might want an additional case for that.

Here, we might again consider renaming the "success" and "failure" values to something more clear.

**Comment by Azquelt** [comment]
After discussion, we came up with these metric names
```
ft.invocations.total{method=<name>, result=[valueReturned|exceptionThrown], fallbackUsed=[true|false]}

ft.retry.calls.total{method=<name>, retryResult=[valueReturned|exceptionNotRetryable|maxRetriesReached|maxDurationReached], retried=true|false}
ft.retry.retries.total{method=<name>}

ft.timeout.calls.total{method=<name>, timedOut=[true|false]}
ft.timeout.executionDuration{method=<name>} (Histogram)

ft.circuitbreaker.calls.total{method=<name>, circuitBreakerResult=[success|failure|circuitBreakerOpen]}
ft.circuitbreaker.state.total{method=<name>, state=[open|halfOpen|closed]}
ft.circuitbreaker.opened.total{method=<name>}

ft.bulkhead.calls.total{method=<name>, bulkheadResult=[accepted, rejected]}
ft.bulkhead.executionsRunning{method=<name>} (Gauge)
ft.bulkhead.executionsWaiting{method=<name>} (Gauge) (*)
ft.bulkhead.runningDuration{method=<name>} (Histogram)
ft.bulkhead.waitingDuration{method=<name>} (Histogram) (*)

(*) Async only
```

**Comment by Ladicek** [comment]
2 things I realized yesterday:

1. I really like folding fallbacks into the overall invocation counter, but what happens if there's no fallback defined for the method? Should we have `fallbackUsed=[none|true|false]` (or `noFallback` instead of `none`)?
2. For retry, I think we didn't quite discuss the proposal of having 2 "layers" of tags, allowing more coarse-grained or more fine-grained views. I think it was something like `ft.retry.calls.total{method=<name>, retryResult=[valueReturned|exceptionThrown], exceptionCause=[exceptionNotRetryable|maxRetriesReached|maxDurationReached], retried=true|false}`, or perhaps `ft.retry.calls.total{method=<name>, retryResult=[success|failure], successReason=[valueReturned|exceptionNotRetryable], failureReason=[maxRetriesReached|maxDurationReached], retried=true|false}` (which uses the dreaded "success" and "failure" terms :-) ).

**Comment by Azquelt** [comment]
I came to start writing this up and realised I'd forgotten you raised these points.

>     1. I really like folding fallbacks into the overall invocation counter, but what happens if there's no fallback defined for the method? Should we have `fallbackUsed=[none|true|false]` (or `noFallback` instead of `none`)?

We could do. I was imagining that `fallbackUsed` would always be `false` if there was no fallback defined.

I guess having a separate state could let you aggregate metrics from multiple methods, some of which use `@Fallback` and some of which don't.

>     2. For retry, I think we didn't quite discuss the proposal of having 2 "layers" of tags, allowing more coarse-grained or more fine-grained views. I think it was something like `ft.retry.calls.total{method=<name>, retryResult=[valueReturned|exceptionThrown], exceptionCause=[exceptionNotRetryable|maxRetriesReached|maxDurationReached], retried=true|false}`, or perhaps `ft.retry.calls.total{method=<name>, retryResult=[success|failure], successReason=[valueReturned|exceptionNotRetryable], failureReason=[maxRetriesReached|maxDurationReached], retried=true|false}` (which uses the dreaded "success" and "failure" terms :-) ).

I'd want to check whether having more tags makes it more difficult to query. I think to use the "simple" tags, you'd have to use `sum()` to make it ignore the "complex" tags.

I think overall I prefer the single tag because it's easy to see that it covers all cases and you don't have to question which tags are meaningful depending on the value of another tag.

**Comment by Azquelt** [comment]
Another thing I noticed while writing this up.

For `ft.circuitbreaker.calls.total`, we use `circuitBreakerResult=circuitBreakerOpen` if the circuit breaker prevents execution. However, executions can also be rejected when the breaker is in half-open state.

**Comment by Ladicek** [comment]
`circuitBreakerOpen` -> `executionPrevented`, I still like it better :-)
