### ISSUE TITLE
We need more microprofile-config tests

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-fault-tolerance#407]
I've noticed that we don't have microprofile-config tests for all MP annotations. 
We need to add more to make sure implementations can actually override all values.

**Comment by Emily-Jiang** [comment]
We also need to test the newly added extra skipOn, failOn etc on `Retry`, `CircuitBreaker`, `Fallback`

**Comment by Emily-Jiang** [comment]
This is to test MP FT annotations can be configured via MP Config. e.g in the following example `
package com.acme;
public class Demo {
@Retry(skipOn="IOException.class", maxRetries=9)
public String myGet() {
...


} 
'
If in a config source, the following property is specified, the skipOn will be RuntimeException instead of IOException.
'com.acme.Demo/myGet/Retry/skipOn=RuntimeException.class'

**Comment by Emily-Jiang** [comment]
@carlosdlr  can you produce a list of tests missing for the existing annotations? @Azquelt will add tests for the new annoations.

**Comment by Azquelt** [comment]
Annotations can be applied to a method, or to a class. In addition, users can configure any parameter globally (for the whole application). So that's three places we can potentially test for each annotation: **method**, **class** and **global**

I think we should concentrate on having full test coverage for annotations at the method level, as that's the most common and easiest to write tests for.

This is our current test coverage for annotations at the **method** level:

- [ ] `Retry`
  - [x] `maxRetries` (covered by `ConfigTest`)
  - [ ] `delay` / `delayUnit`
  - [ ] `maxDuration` / `durationUnit` (`maxDuration` only covered by `ConfigTest`)
  - [ ] `jitter` / `jitterDelayUnit`
  - [ ] `retryOn`
  - [ ] `abortOn`
- [ ] `CircuitBreaker` (`CircuitBreakerConfigTest`)
  - [ ] `failOn`
  - [x] `skipOn`
  - [ ] `delay` / `delayUnit`
  - [ ] `requestVolumeThreshold`
  - [ ] `successThreshold`
- [ ] `Timeout`
  - [ ] `value` / `unit` (`value` only covered by `TimeoutMethodConfigTest`)
- [ ] `Bulkhead`
  - [x] `value` (covered by `BulkheadSynchConfigTest`)
  - [ ] `waitingTaskQueue`
- [ ] `Fallback` (`FallbackConfigTest`)
  - [ ] `value` (i.e. defining a `FallbackHandler`)
  - [ ] `fallbackMethod`
  - [x] `applyOn`
  - [x] `skipOn`

In addition, we have the following test classes which test other aspects of config
* `ConfigTest` (mentioned above, covers `Retry.maxRetries` and `Retry.maxDuration` at the class and method level)
* `TimeoutMethodConfigTest` (mentioned above, covers `Timeout.value` at the method level)
* `TimeoutGlobalConfigTest` (covers `Timeout.value` at the global level`)
* `ConfigPropertyGlobalVsClassTest` (checks that config at the method level overrides config at the global level)
* `ConfigPropertyOnClassAndMethodTest` (checks that config at the method level overrides config at the class level. I think this is irrelevant because config at the class level should never affect an annotation on a method)
* `ConfigPropertyGlobalVsClassVsMethodTest` (checks that config at the method level overrides config at both the class and global level. Might be a bit redundant.)
* `FallbackSkipOnConfigTest` (covers `Fallback.skipOn` at the global level)
* `FallbackApplyOnConfigTest` (covers `Fallback.applyOn` at the global level)
* `CircuitBreakerSkipOnConfigTest` (covers `CircuitBreaker.skipOn` at the global level)

I'd recommend writing new tests for the parameters which are not currently covered at the method level, following the example of `FallbackConfigTest` and `CircuitBreakerConfigTest`.

**Comment by Ladicek** [comment]
I have just merged my PRs for timeout and circuit breaker and it seems this is done, yay! :-)

**Comment by Azquelt** [comment]
I agree, I think this issue is done!
