### ISSUE TITLE
@Timeout behavior without @Asynchronous

### ISSUE THREAD

**Issue by michalszynkiewicz** [eclipse/microprofile-fault-tolerance#408]
I wasn't able to find any info in the spec that would say that a method annotated with `@Timeout` should block until the execution is finished if the execution is non interruptible, yet the last assertion in `TimeoutUninterruptableTest#testTimeout` checks that.
Does it mean that `@Timeout` without `@Asynchronous` has to be executed on the callers thread?

**Comment by Azquelt** [comment]
All methods without `@Asynchronous` will be executed on the callers thread.

The 2.0 spec says this (Chapter 6):
> When `@Timeout` is used without `@Asynchronous`, the current thread will be interrupted with a call to `Thread.interrupt()` on reaching the specified timeout duration. The interruption will only work in
certain scenarios. The interruption will not work for the following situations:
> * The thread is blocked on blocking I/O (database, file read/write), an exception is thrown only in
case of waiting for a NIO channel
> * The thread isn’t waiting (CPU intensive task) and isn’t checking for being interrupted
> * The thread will catch the interrupted exception (with a general catch block) and will just
continue processing, ignoring the interrupt
> 
> In the above situations, it is impossible to suspend the execution. The execution thread will finish
its process. If the execution takes longer than the specified timeout, the TimeoutException will be
thrown and the execution result will be discarded.
> 
> If a timeout occurs, the thread interrupted status must be cleared when the method returns.

**Comment by kenfinnigan** [comment]
Isn't that limiting though, forcing implementations as to how to manage threads?

**Comment by Azquelt** [comment]
In general, I don't think we want to end up in a situation where the user's code runs asynchronously when they expected it to run synchronously because they won't have considered whether their code is thread safe.

I can see that blocking the calling thread only until the timeout expires seems to make sense (and may often be the desired behaviour), but the user still needs to ensure that there's no risk of changing some shared state in an unsynchronised way after the timeout has fired.

If the user wants to ensure that the timeout fires even when their code is running a blocking operation, they can use `@Asynchronous` as well as `@Timeout` and make a conscious choice to run their code asynchronously.

Using `@Asynchronous` does require returning a `Future` or `CompletionStage` which makes certain things (such as exception handling) more complicated, so maybe it would make sense to add some way of doing this without incurring those penalties to the spec in a future version?

**Comment by Emily-Jiang** [comment]
@michalszynkiewicz are you implementing this spec and considering launching the method with `@Timeout` asynchronously?

**Comment by michalszynkiewicz** [comment]
That's what we currently do in SmallRye.

If `@Timeout` should by default be run in the callers thread, I think we should add a test to the TCK that would test explicitly that.

**Comment by Emily-Jiang** [comment]
@michalszynkiewicz can you attend our weekly meeting this week on Wednesday 2-3pm UK time to discuss this a bit further? 

Hangout link: https://eclipse.zoom.us/j/949859967 Minutes: https://docs.google.com/document/d/12Tm_JP2Ws8W1fU5IIhhIbNHbrEIf27wgTbTIv80JoXY/edit

**Comment by Emily-Jiang** [comment]
@michalszynkiewicz 

> That's what we currently do in SmallRye.

If @Timeout should by default be run in the callers thread, I think we should add a test to the TCK that would test explicitly that.

**Comment by michalszynkiewicz** [comment]
We discussed this issue on the call yesterday.
I still believe that what we want for the user is to have the caller's CDI context available in the execution and it should not matter if the execution happens on the same thread or not.
It was pointed out that having it on the same thread is a simpler concept to grasp for the user and its easier to implement.
The conclusion was to leave the spec and the test as it is and to revisit it when the spec will be modified to fit the reactive model.
@Emily-Jiang please correct me if I missed something.

**Comment by Emily-Jiang** [comment]
Thanks @michalszynkiewicz ! I will close this one and we can always revisit if a new use case comes up.
