### ISSUE TITLE
Define events for Faults

### ISSUE THREAD

**Issue by Pscheidl** [eclipse/microprofile-fault-tolerance#48]
Whenever there is fault-tolerance error, an event should be fired.

- Client application can easily observe and process the failsafe data
- Hooks for other libraries/dashboard will be easier to create
- Hooks should be asynchronous - CDI 2. Blocking execution of business code in order to handle event observers is not acceptable.

Example with event fired thrown after an exception is thrown can be found in [FortEE](https://github.com/Pscheidl/FortEE/blob/master/src/main/java/com/github/pscheidl/fortee/FailsafeInterceptor.java)

In case of Microprofile fault tolerance, there could be more types of events:

- Circuit opened
- Circuit closed
- Exception thrown
- Timeout reached

**Comment by Emily-Jiang** [comment]
@Pscheidl thanks for raising this issue! Can you take a look at the proposal in one of my [PRs](https://github.com/eclipse/microprofile-fault-tolerance/pull/22). It was not merged as there was a doubt on how useful an event is. Would the APIs in my PR is similar to what you have in mind? 

I think: CircuitOpen, CircuitClose, TimeOut, MaxRetries reached all fire events. Do you have some examples on how a monitoring agent can utilise this event and pipe them through to dashboard?

**Comment by Ladicek** [comment]
I used to have a CDI event in SmallRye Fault Tolerance for circuit breaker state changes. I got rid of it, because it was ugly for the main usecase I intended: access state of given circuit breaker. I moved to a different model: https://smallrye.io/docs/smallrye-fault-tolerance/5.2.0/usage/extra.html#_circuit_breaker_maintenance (Something similar could be devised for bulkheads.)
