### ISSUE TITLE
Missing descriptions in for Fault Tolerance parameters

### ISSUE THREAD

**Issue by dmuelle** [eclipse/microprofile-fault-tolerance#485]
In the Open Liberty javadoc, a number of Fault Tolerance annotation parameters are missing descriptions in the autogen `Optional Elements` tables for each annotation. The descriptions are present in the element detail but missing from the table.

[Circuit Breaker](https://openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/faulttolerance/package-frame.html&class=org/eclipse/microprofile/faulttolerance/CircuitBreaker.html)

`delayUnit`

[Retry](https://openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/faulttolerance/package-frame.html&class=org/eclipse/microprofile/faulttolerance/Retry.html)

`delayUnit`
`durationUnit`
`jitterDelayUnit`
`retryOn`

[Timeout](https://openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/faulttolerance/package-frame.html&class=org/eclipse/microprofile/faulttolerance/Timeout.html)

`unit`

**Comment by Ladicek** [comment]
Should be filed in OpenLiberty bug tracker?

**Comment by Azquelt** [comment]
The issues with `Retry` and `Timeout` are also present in the javadoc on eclipse.org

[Retry](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0.2/apidocs/index.html?org/eclipse/microprofile/faulttolerance/Retry.html)
[Timeout](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0.2/apidocs/index.html?org/eclipse/microprofile/faulttolerance/Timeout.html)

The issue with `CircuitBreaker` was fixed at some point between 2.0 and 2.0.1.

I think this happens when the annotation parameter just has an `@return` line and no other text.

I think the openliberty.io site just builds the javadocs based on the dependencies of the umbrella microprofile artifact, and that's still pulling in the 2.0 version of the API without the `CircuitBreaker` fix.

So, it might be good to raise an issue on the openliberty.io site to pull in the latest micro release of each spec, rather than the version in the umbrella artifact, but the javadoc for `Retry` and `Timeout` also need fixed here.

As a side note, it would be nice there was an easy to find official location of all the microprofile javadoc, (say, linked from microprofile.io) rather than having to fish around download.eclipse.org to find it.

**Comment by Emily-Jiang** [comment]
Let's fix in the spec. @Azquelt I have been working with @rstjames for the microprofile.io page redesign see https://github.com/microprofile/microprofile-site/issues/87. Feel free to add any comments there.
