### ISSUE TITLE
Provide a way to switch off FT policy except retry

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#58]
[Istio integration discussion](https://groups.google.com/forum/#!searchin/microprofile/Istio%7Csort:relevance/microprofile/O8qqDFCtsFo/oi1QdMHRBAAJ) lists a few options to support Istio integration.

If a microservice app is deployed to Istio, Istio would like to switch off MicroProfile FT feature except fallback. We need to provide a way to do so, e.g. a config property.

**Comment by johnament** [comment]
We should not be specifying integration to an existing 3rd party component.

**Comment by Emily-Jiang** [comment]
We need to provide a way to switch off the FT feature like what CDI spec does. This is a really useful feature.

**Comment by kenfinnigan** [comment]
Is it integration with Istio or just delegation to?

Personally I see this as the latter

**Comment by Emily-Jiang** [comment]
@kenfinnigan the latter.

**Comment by johnament** [comment]
I'm still whole heartedly against us specifying direct integration or behavior when used with any specific platform.

And this still seems to be an implementation specific problem.  I'm looking at istio (which is just 0.2) and it seems like it has no relevance for FT.  In addition, why are we saying that the behavior has to be off?

**Comment by Emily-Jiang** [comment]
@johnament https://istio.io/docs/concepts/traffic-management/rules-configuration.html#timeouts-and-retries

**Comment by jclingan** [comment]
@johnament I know IBM and Red Hat are both interested in Istio, although not even all our customers will deploy to Istio. We should not force a solution on all of MP users to address this use case, but I think service meshes are going to become an increasingly popular use case for MP users over the next 12 months.  

 If the FT team thinks it is too early and that we are prematurely optimizing for this use case, I can understand that position, especially if it requires a lot of re-work around FT implementations (failsafe or Hystrix for example).  However, I think the MicroProfile and service mesh communities (including Linkerd) should be chatting quite closely since there are potentially significant areas of interest (FT, service discovery, load balancing, and distributed tracing being four off the top of my head).

**Comment by Emily-Jiang** [comment]
Included this requirement to the spec.
