### ISSUE TITLE
Work with MicroProfile Telemetry Metrics

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#622]
**Description**

As a:

- [ ] API User (application developer)
- [ ] Specification Implementer

...I need to be able to:

get OpenTelemetry metrics

...which enables me to:

get unified metrics

**Comment by benjamin-confino** [comment]
I did an experiment in OpenLiberty and was able to modify our integration layer between mpFaultTolerence and mpMetrics to use telemetry metrics with minimal changes. I think we can resolve this issue without changing the fault tolerance code.

-----------

Tasks that must be acomplished: 

[] Add a section to the fault tolerence specifications covering FT and telemetry integration. 
[] Add a package to the TCK to test FT and telemetry integration. 

--------

Discussion points

[] Do we want to add or modify the metrics Fault Tolerence records?
[] What happens if both MP Telemetry and MP Metrics are enabled for the first time?

**Comment by benjamin-confino** [comment]
https://github.com/eclipse/microprofile-fault-tolerance/pull/623 Resolves this issue.

**Comment by Azquelt** [comment]
Do we need/want a new config option to allow the export of metrics to telemetry to be disabled? (like https://download.eclipse.org/microprofile/microprofile-fault-tolerance-4.0.2/microprofile-fault-tolerance-spec-4.0.2.html#_configuring_metrics_integration)

**Comment by benjamin-confino** [comment]
I think if that option was useful for MP Metrics it will be useful for MP Telemetry. For simplicity I would suggest we use the same property for both, and update the spec to say it covers both.

**Comment by Azquelt** [comment]
Is this issue complete?

**Comment by Azquelt** [comment]
The work here is complete, #623 updated the spec and added TCKs.
